program biodata;
uses crt;

begin
     clrscr;
     writeln('BIODATA MAHASISWA');
     writeln('1. NAMA   : AEF SYAEFUDDIN ZUHRI');
     writeln('2. NPM    : 20.14.1.0018');
     writeln('3. ALAMAT : DESA MUNJUL');
     writeln('4. TTL    : MAJALENGKA, 25-10-1997');
     writeln('5. NO. HP : 0823 1835 5747');
     writeln('6. MOTTO  : SEBAIK-BAIK MANUSIA ADALAH YANG PALING BERMANFAAT UNTUK ORANG LAIN');
     readln;
end.